language: cpp
os: linux
sudo: required
services:
  - docker

if: tag IS blank

matrix:
  include:
  # Clang 6.0
  - compiler: clang
    env: DIST=ubuntu:17.10 INSTALL='clang-6.0 libc++-dev libc++abi-dev' BJAM_COMPILER=clang
  # GCC 7
  - compiler: gcc
    env: DIST=ubuntu:17.10 INSTALL=g++ BJAM_COMPILER=gcc

before_install:
  - |
    PATTERN="s/ubuntu:17.10/$DIST/;s/g++/$INSTALL/;s/gcc/$BJAM_COMPILER/g"
    echo "$PATTERN"
    sed "$PATTERN" Dockerfile > $BJAM_COMPILER.dockerfile
    if [ "$BJAM_COMPILER" = clang ]; then
      wget -O llvm-snapshot.gpg.key https://apt.llvm.org/llvm-snapshot.gpg.key
      sed -i \
        -e '4iCOPY llvm-snapshot.gpg.key .\nRUN apt-key add llvm-snapshot.gpg.key' \
        -e '/mkdir/iRUN sed -i -e "s/__GLIBC__) || defined(//" /usr/include/c++/v1/__locale' \
        -e 's/^# clang: //' \
        $BJAM_COMPILER.dockerfile
      echo -e 'using clang : : clang++-6.0 : <cxxflags>-fdiagnostics-color=always <cxxflags>-stdlib=libc++ <cxxflags>-Wunused-command-line-argument <linkflags>-stdlib=libc++ ;' > project-config.jam
    else
      echo -e 'using gcc : : g++-7 : <cxxflags>-fdiagnostics-color=always ;' > project-config.jam
    fi
  - cat $BJAM_COMPILER.dockerfile
  - cat project-config.jam
  - docker pull $DIST

script:
  - docker build -f $BJAM_COMPILER.dockerfile .

# branches:
#   except:
#     - /^[0-9]/

notifications:
  email:
    recipients:
      - jpoelen@wallix.com
      - rzhou@wallix.com
      - cgrosjean@wallix.com
      - cmoroldo@wallix.com
      #- mtan@wallix.com
    on_success: change
    on_failure: always
